// <auto-generated />
using System;
using ActionLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ActionLedger.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922021601_AddMeetings")]
    partial class AddMeetings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActionLedger.Domain.Meetings.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Attendees")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("attendees");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("date")
                        .HasColumnName("meeting_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_meetings");

                    b.HasIndex("Title", "MeetingDate")
                        .IsUnique()
                        .HasDatabaseName("ix_meetings_title_meeting_date");

                    b.ToTable("meetings");
                });

            modelBuilder.Entity("ActionLedger.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ActionLedger.Domain.Meetings.Meeting", b =>
                {
                    b.OwnsOne("ActionLedger.Domain.Meetings.MeetingNotes", "Notes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("MeetingId")
                                .HasColumnType("uuid")
                                .HasColumnName("meeting_id");

                            b1.Property<DateTimeOffset>("SavedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("saved_at");

                            b1.Property<string>("Sha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("sha256")
                                .IsFixedLength();

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(50000)
                                .HasColumnType("character varying(50000)")
                                .HasColumnName("text");

                            b1.HasKey("Id")
                                .HasName("pk_meeting_notes");

                            b1.HasIndex("MeetingId")
                                .IsUnique()
                                .HasDatabaseName("ix_meeting_notes_meeting_id");

                            b1.ToTable("meeting_notes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MeetingId")
                                .HasConstraintName("fk_meeting_notes_meetings_meeting_id");
                        });

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
