// <auto-generated />
using System;
using ActionLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ActionLedger.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActionLedger.Domain.Actions.ActionRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_action_revisions");

                    b.HasIndex("TargetType", "TargetId", "Sequence")
                        .HasDatabaseName("ix_action_revisions_target_type_target_id_sequence");

                    b.ToTable("action_revisions");
                });

            modelBuilder.Entity("ActionLedger.Domain.Extraction.ExtractionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<Guid>("MeetingNotesId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_notes_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("NotesSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("notes_sha256")
                        .IsFixedLength();

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StartedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("started_by_user_id");

                    b.PrimitiveCollection<string[]>("Warnings")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("warnings");

                    b.HasKey("Id")
                        .HasName("pk_extraction_runs");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_extraction_runs_meeting_id");

                    b.ToTable("extraction_runs");
                });

            modelBuilder.Entity("ActionLedger.Domain.Extraction.ProposedAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("ExtractionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("extraction_run_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("ReviewState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("review_state");

                    b.Property<string>("SourceExcerpt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_excerpt");

                    b.Property<DateOnly?>("SuggestedDueDate")
                        .HasColumnType("date")
                        .HasColumnName("suggested_due_date");

                    b.Property<string>("SuggestedOwner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("suggested_owner");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_proposed_actions");

                    b.HasIndex("ExtractionRunId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_proposed_actions_extraction_run_id_ordinal");

                    b.ToTable("proposed_actions", (string)null);
                });

            modelBuilder.Entity("ActionLedger.Domain.Meetings.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Attendees")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("attendees");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("date")
                        .HasColumnName("meeting_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_meetings");

                    b.HasIndex("Title", "MeetingDate")
                        .IsUnique()
                        .HasDatabaseName("ix_meetings_title_meeting_date");

                    b.ToTable("meetings");
                });

            modelBuilder.Entity("ActionLedger.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ActionLedger.Domain.Extraction.ProposedAction", b =>
                {
                    b.HasOne("ActionLedger.Domain.Extraction.ExtractionRun", null)
                        .WithMany("Proposals")
                        .HasForeignKey("ExtractionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proposed_actions_extraction_runs_extraction_run_id");
                });

            modelBuilder.Entity("ActionLedger.Domain.Meetings.Meeting", b =>
                {
                    b.OwnsOne("ActionLedger.Domain.Meetings.MeetingNotes", "Notes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("MeetingId")
                                .HasColumnType("uuid")
                                .HasColumnName("meeting_id");

                            b1.Property<DateTimeOffset>("SavedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("saved_at");

                            b1.Property<string>("Sha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .HasColumnName("sha256")
                                .IsFixedLength();

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(50000)
                                .HasColumnType("character varying(50000)")
                                .HasColumnName("text");

                            b1.HasKey("Id")
                                .HasName("pk_meeting_notes");

                            b1.HasIndex("MeetingId")
                                .IsUnique()
                                .HasDatabaseName("ix_meeting_notes_meeting_id");

                            b1.ToTable("meeting_notes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MeetingId")
                                .HasConstraintName("fk_meeting_notes_meetings_meeting_id");
                        });

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("ActionLedger.Domain.Extraction.ExtractionRun", b =>
                {
                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
