using System.Security.Cryptography;
using System.Text;
using ActionLedger.Application.Abstractions;
using ActionLedger.Application.Meetings;
using ActionLedger.Domain.Meetings;
using ActionLedger.Infrastructure.Persistence;
using ActionLedger.Infrastructure.Persistence.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.DependencyInjection;
using Npgsql;
using Xunit;

namespace ActionLedger.Infrastructure.Tests;

/// <summary>
/// AD-10, AD-17, and AD-20 for the Meeting aggregate against a real PostgreSQL 18: the migration
/// produces the columns and indexes the conventions promise, a new Meeting with its notes persists
/// as inserts only, both unique indexes surface as
/// <see cref="ConcurrencyConflictException"/>, and the notes come back byte-for-byte.
/// </summary>
[Collection(PostgresFixture.CollectionName)]
public sealed class MeetingPersistenceTests(PostgresFixture postgres)
{
    private static readonly DateOnly Held = new(2026, 9, 18);

    private static readonly DateTimeOffset Created = new(2026, 9, 18, 14, 30, 0, TimeSpan.Zero);

    [Fact]
    public async Task The_migration_creates_meetings_with_snake_case_columns()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        string connectionString = await MigratedDatabaseAsync(nameof(The_migration_creates_meetings_with_snake_case_columns), cancellationToken);

        Dictionary<string, string> columns = await ColumnsAsync(connectionString, "meetings", cancellationToken);

        Assert.Equal(
            ["attendees", "created_at", "created_by_user_id", "id", "meeting_date", "title"],
            columns.Keys.Order(StringComparer.Ordinal));

        Assert.Equal("uuid", columns["id"]);
        Assert.Equal("uuid", columns["created_by_user_id"]);
        Assert.Equal("character varying", columns["title"]);

        // AD-10's type rows: a calendar day is `date`, an instant is `timestamptz`, and a list of
        // names is a PostgreSQL array rather than a delimited string or a JSON blob.
        Assert.Equal("date", columns["meeting_date"]);
        Assert.Equal("timestamp with time zone", columns["created_at"]);
        Assert.Equal("ARRAY", columns["attendees"]);
    }

    [Fact]
    public async Task The_concurrency_token_is_the_system_column_not_one_the_migration_added()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        string connectionString = await postgres.CreateDatabaseAsync(nameof(The_concurrency_token_is_the_system_column_not_one_the_migration_added), cancellationToken);

        await using ServiceProvider services = TestHost.Build(connectionString, TestHost.SeedingOff);
        await TestHost.MigrateAsync(services, cancellationToken);

        await using AsyncServiceScope scope = services.CreateAsyncScope();

        // The absence check below is satisfied just as happily by a Meeting that has no token at
        // all, so it cannot stand alone: delete the two lines in MeetingConfiguration that set
        // this and nothing would notice. This is the half that says the token exists.
        IProperty? token = scope.ServiceProvider.GetRequiredService<AppDbContext>()
            .Model
            .FindEntityType(typeof(Meeting))!
            .FindProperty(MeetingConfiguration.ConcurrencyTokenProperty);

        Assert.NotNull(token);
        Assert.True(token.IsConcurrencyToken);

        // Generated by the database on every write, which is what makes it a row version rather
        // than a value the model would have to maintain.
        Assert.Equal(ValueGenerated.OnAddOrUpdate, token.ValueGenerated);
        Assert.Equal(MeetingConfiguration.ConcurrencyTokenProperty, token.GetColumnName());

        Dictionary<string, string> columns = await ColumnsAsync(connectionString, "meetings", cancellationToken);

        // AD-20 puts `xmin` on Meeting. PostgreSQL already has a system column by that name, so a
        // real column would have failed the CREATE TABLE outright — this is what proves the token
        // is bound to the system column rather than shadowing it.
        Assert.DoesNotContain(MeetingConfiguration.ConcurrencyTokenProperty, columns.Keys);
    }

    [Fact]
    public async Task The_migration_creates_meeting_notes_with_snake_case_columns()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        string connectionString = await MigratedDatabaseAsync(nameof(The_migration_creates_meeting_notes_with_snake_case_columns), cancellationToken);

        Dictionary<string, string> columns = await ColumnsAsync(connectionString, "meeting_notes", cancellationToken);

        Assert.Equal(
            ["id", "meeting_id", "saved_at", "sha256", "text"],
            columns.Keys.Order(StringComparer.Ordinal));

        Assert.Equal("uuid", columns["id"]);
        Assert.Equal("uuid", columns["meeting_id"]);
        Assert.Equal("character varying", columns["text"]);
        Assert.Equal("character", columns["sha256"]);
        Assert.Equal("timestamp with time zone", columns["saved_at"]);
    }

    [Theory]
    [InlineData("meetings", MeetingConfiguration.TitleAndDateIndexName, "title")]
    [InlineData("meeting_notes", MeetingConfiguration.NotesMeetingIndexName, "meeting_id")]
    public async Task The_AD20_unique_indexes_exist_by_name(string table, string index, string column)
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        string connectionString = await MigratedDatabaseAsync($"indexes_{table}", cancellationToken);

        await using NpgsqlConnection connection = new(connectionString);
        await connection.OpenAsync(cancellationToken);

        await using NpgsqlCommand command = new(
            """
            SELECT indexdef
            FROM pg_indexes
            WHERE schemaname = 'public' AND tablename = @table AND indexname = @name
            """,
            connection);

        command.Parameters.AddWithValue("table", table);
        command.Parameters.AddWithValue("name", index);

        string? definition = (string?)await command.ExecuteScalarAsync(cancellationToken);

        Assert.NotNull(definition);
        Assert.Contains("UNIQUE", definition, StringComparison.Ordinal);
        Assert.Contains(column, definition, StringComparison.Ordinal);
    }

    [Fact]
    public async Task A_meeting_and_its_notes_persist_as_inserts_only()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        RecordingCommandInterceptor recorder = new();

        await using ServiceProvider services = await MigratedHostAsync(
            nameof(A_meeting_and_its_notes_persist_as_inserts_only),
            cancellationToken,
            collection => collection.ConfigureDbContext<AppDbContext>(options => options.AddInterceptors(recorder)));

        // Migrating is a wall of DDL. Only what the write itself sends is of interest.
        recorder.Clear();

        Meeting meeting = NewMeeting("Weekly sync");
        meeting.AttachNotes("Dana will send the draft by Friday.", Created);

        await using (AsyncServiceScope scope = services.CreateAsyncScope())
        {
            scope.ServiceProvider.GetRequiredService<IMeetingRepository>().Add(meeting);
            await scope.ServiceProvider.GetRequiredService<IUnitOfWork>().CommitAsync(cancellationToken);
        }

        string[] touching =
        [
            .. recorder.Commands.Where(command =>
                command.Contains("meetings", StringComparison.OrdinalIgnoreCase)
                || command.Contains("meeting_notes", StringComparison.OrdinalIgnoreCase)),
        ];

        Assert.NotEmpty(touching);
        Assert.Contains(touching, command => command.Contains("INSERT INTO", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(touching, command => command.Contains("UPDATE ", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public async Task The_persisted_ids_are_the_uuidv7s_the_domain_constructors_made()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        await using ServiceProvider services = await MigratedHostAsync(nameof(The_persisted_ids_are_the_uuidv7s_the_domain_constructors_made), cancellationToken);

        Meeting meeting = NewMeeting("Weekly sync");
        MeetingNotes notes = meeting.AttachNotes("Dana will send the draft by Friday.", Created);

        Guid meetingId = meeting.Id;
        Guid notesId = notes.Id;

        await SaveAsync(services, meeting, cancellationToken);

        Meeting stored = await ReadAsync(services, meetingId, cancellationToken);

        Assert.Equal(meetingId, stored.Id);
        Assert.True(stored.HasNotes);
        Assert.Equal(notesId, stored.Notes!.Id);
        Assert.Equal(meetingId, stored.Notes.MeetingId);

        // Version 7: the nibble the UUIDv7 layout puts in byte 6. EF generated nothing, or these
        // would be database-side values with a different version.
        Assert.Equal(7, (stored.Id.ToByteArray(bigEndian: true)[6] & 0xF0) >> 4);
        Assert.Equal(7, (stored.Notes.Id.ToByteArray(bigEndian: true)[6] & 0xF0) >> 4);
    }

    [Theory]
    [InlineData("  leading and trailing  ")]
    [InlineData("first line\r\nsecond line\r\n")]
    [InlineData("mixed\r\nline\nendings\r\n   ")]
    public async Task Notes_round_trip_byte_for_byte(string pasted)
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        // A content-derived suffix so each theory row gets its own database. It is a digest rather
        // than string.GetHashCode, which is salted per process: that gave every run a different
        // database name, and a negative hash put a hyphen in the identifier.
        string suffix = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(pasted)))[..8];

        await using ServiceProvider services = await MigratedHostAsync(
            $"{nameof(Notes_round_trip_byte_for_byte)}_{suffix}",
            cancellationToken);

        Meeting meeting = NewMeeting("Weekly sync");
        meeting.AttachNotes(pasted, Created);

        await SaveAsync(services, meeting, cancellationToken);

        Meeting stored = await ReadAsync(services, meeting.Id, cancellationToken);

        Assert.Equal(pasted, stored.Notes!.Text);
        Assert.Equal(Encoding.UTF8.GetBytes(pasted), Encoding.UTF8.GetBytes(stored.Notes.Text));

        // And the hash that came back is still the hash of what came back, so a row that had been
        // altered in the database could not pass as intact.
        Assert.Equal(
            Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(stored.Notes.Text))),
            stored.Notes.Sha256);
    }

    [Fact]
    public async Task Attendees_round_trip_as_an_array_including_the_empty_one()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        await using ServiceProvider services = await MigratedHostAsync(nameof(Attendees_round_trip_as_an_array_including_the_empty_one), cancellationToken);

        Meeting withAttendees = Meeting.Create("Weekly sync", Held, ["Dana Whitfield", "Marcus Bell"], Guid.CreateVersion7(), Created);
        Meeting without = Meeting.Create("Solo review", Held, null, Guid.CreateVersion7(), Created);

        await SaveAsync(services, withAttendees, cancellationToken);
        await SaveAsync(services, without, cancellationToken);

        Assert.Equal(
            ["Dana Whitfield", "Marcus Bell"],
            (await ReadAsync(services, withAttendees.Id, cancellationToken)).Attendees);

        Assert.Empty((await ReadAsync(services, without.Id, cancellationToken)).Attendees);
    }

    [Fact]
    public async Task A_duplicate_title_on_the_same_day_surfaces_as_a_concurrency_conflict()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        await using ServiceProvider services = await MigratedHostAsync(nameof(A_duplicate_title_on_the_same_day_surfaces_as_a_concurrency_conflict), cancellationToken);

        await SaveAsync(services, NewMeeting("Weekly sync"), cancellationToken);

        await using AsyncServiceScope second = services.CreateAsyncScope();
        second.ServiceProvider.GetRequiredService<IMeetingRepository>().Add(NewMeeting("Weekly sync"));

        ConcurrencyConflictException conflict = await Assert.ThrowsAsync<ConcurrencyConflictException>(
            () => second.ServiceProvider.GetRequiredService<IUnitOfWork>().CommitAsync(cancellationToken));

        // AD-1: no EF Core or Npgsql type may reach Application. The provider's exception is the
        // inner one, and it stops here.
        Assert.IsAssignableFrom<DbUpdateException>(conflict.InnerException);
    }

    [Fact]
    public async Task The_same_title_on_another_day_is_not_a_duplicate()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        await using ServiceProvider services = await MigratedHostAsync(nameof(The_same_title_on_another_day_is_not_a_duplicate), cancellationToken);

        await SaveAsync(services, Meeting.Create("Weekly sync", Held, null, Guid.CreateVersion7(), Created), cancellationToken);
        await SaveAsync(services, Meeting.Create("Weekly sync", Held.AddDays(7), null, Guid.CreateVersion7(), Created), cancellationToken);

        await using AsyncServiceScope scope = services.CreateAsyncScope();

        Assert.Equal(2, await scope.ServiceProvider.GetRequiredService<AppDbContext>().Meetings.CountAsync(cancellationToken));
    }

    [Fact]
    public async Task Two_writers_attaching_notes_to_the_same_meeting_end_in_one_conflict()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        await using ServiceProvider services = await MigratedHostAsync(nameof(Two_writers_attaching_notes_to_the_same_meeting_end_in_one_conflict), cancellationToken);

        Meeting meeting = NewMeeting("Weekly sync");
        await SaveAsync(services, meeting, cancellationToken);

        // Both scopes read the Meeting before either wrote, so the aggregate's own rule says yes
        // to both. The unique index on meeting_notes(meeting_id) is the only thing left.
        await using AsyncServiceScope first = services.CreateAsyncScope();
        await using AsyncServiceScope second = services.CreateAsyncScope();

        Meeting forFirst = await LoadAsync(first, meeting.Id, cancellationToken);
        Meeting forSecond = await LoadAsync(second, meeting.Id, cancellationToken);

        Assert.False(forFirst.HasNotes);
        Assert.False(forSecond.HasNotes);

        forFirst.AttachNotes("The first paste.", Created);
        await first.ServiceProvider.GetRequiredService<IUnitOfWork>().CommitAsync(cancellationToken);

        forSecond.AttachNotes("The second paste.", Created);

        ConcurrencyConflictException conflict = await Assert.ThrowsAsync<ConcurrencyConflictException>(
            () => second.ServiceProvider.GetRequiredService<IUnitOfWork>().CommitAsync(cancellationToken));

        Assert.IsAssignableFrom<DbUpdateException>(conflict.InnerException);

        // And the first paste is what a read still returns.
        Assert.Equal("The first paste.", (await ReadAsync(services, meeting.Id, cancellationToken)).Notes!.Text);
    }

    [Fact]
    public async Task A_meeting_loads_with_its_notes_so_the_write_once_rule_can_see_them()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        await using ServiceProvider services = await MigratedHostAsync(nameof(A_meeting_loads_with_its_notes_so_the_write_once_rule_can_see_them), cancellationToken);

        Meeting meeting = NewMeeting("Weekly sync");
        meeting.AttachNotes("The first paste.", Created);

        await SaveAsync(services, meeting, cancellationToken);

        // No Include, exactly as SaveMeetingNotesHandler calls it. The notes are an owned type, so
        // they come with the root — which is what makes the second save a 409 rather than a second
        // row nobody's rule stopped.
        await using AsyncServiceScope scope = services.CreateAsyncScope();

        Assert.True((await LoadAsync(scope, meeting.Id, cancellationToken)).HasNotes);
    }

    [Fact]
    public async Task The_list_query_translates_to_sql_and_orders_the_way_it_promises()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        await using ServiceProvider services = await MigratedHostAsync(nameof(The_list_query_translates_to_sql_and_orders_the_way_it_promises), cancellationToken);

        await SaveAsync(services, Meeting.Create("Older day", new DateOnly(2026, 9, 16), null, Guid.CreateVersion7(), Created), cancellationToken);
        await SaveAsync(services, Meeting.Create("Earlier", Held, null, Guid.CreateVersion7(), Created.AddHours(-2)), cancellationToken);
        await SaveAsync(services, Meeting.Create("Later", Held, ["Dana Whitfield"], Guid.CreateVersion7(), Created), cancellationToken);

        await using AsyncServiceScope scope = services.CreateAsyncScope();

        // The Application-ring fake is LINQ to Objects, so the ordering and the projection are
        // only proven to be a *query* there. This is what proves the provider can translate them.
        PagedResult<MeetingSummaryDto> page = await QueriesIn(scope).ListAsync(null, null, cancellationToken);

        Assert.Equal(["Later", "Earlier", "Older day"], page.Items.Select(meeting => meeting.Title));
        Assert.Equal(3, page.Total);
        Assert.All(page.Items, meeting =>
        {
            Assert.Equal(0, meeting.RunCount);
            Assert.Equal(0, meeting.TrackedActionCount);
        });
    }

    [Fact]
    public async Task The_detail_query_translates_to_sql_and_carries_the_notes_and_the_attendees()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        await using ServiceProvider services = await MigratedHostAsync(nameof(The_detail_query_translates_to_sql_and_carries_the_notes_and_the_attendees), cancellationToken);

        Meeting withNotes = NewMeeting("Weekly sync");
        MeetingNotes notes = withNotes.AttachNotes("  Dana will send the draft.\r\n", Created);
        await SaveAsync(services, withNotes, cancellationToken);

        Meeting withoutNotes = Meeting.Create("Solo review", Held, null, Guid.CreateVersion7(), Created);
        await SaveAsync(services, withoutNotes, cancellationToken);

        await using AsyncServiceScope scope = services.CreateAsyncScope();
        MeetingsQueries queries = QueriesIn(scope);

        MeetingDetailDto detail = await queries.GetAsync(withNotes.Id, cancellationToken);

        Assert.Equal(["Dana Whitfield"], detail.Attendees);
        Assert.Equal(withNotes.CreatedByUserId, detail.CreatedByUserId);
        Assert.NotNull(detail.Notes);
        Assert.Equal(notes.Id, detail.Notes.Id);
        Assert.Equal("  Dana will send the draft.\r\n", detail.Notes.Text);
        Assert.Equal(notes.Sha256, detail.Notes.Sha256);

        // A Meeting with no notes projects a null rather than an empty object or a missing row.
        MeetingDetailDto bare = await queries.GetAsync(withoutNotes.Id, cancellationToken);

        Assert.Null(bare.Notes);
        Assert.Empty(bare.Attendees);
    }

    [Fact]
    public async Task The_detail_query_answers_an_unknown_id_with_a_not_found()
    {
        CancellationToken cancellationToken = TestContext.Current.CancellationToken;
        await using ServiceProvider services = await MigratedHostAsync(nameof(The_detail_query_answers_an_unknown_id_with_a_not_found), cancellationToken);

        await using AsyncServiceScope scope = services.CreateAsyncScope();

        await Assert.ThrowsAsync<NotFoundException>(() =>
            QueriesIn(scope).GetAsync(Guid.CreateVersion7(), cancellationToken));
    }

    /// <summary>
    /// The query class over the real read seam. It is registered by the Application ring's own
    /// <c>AddActionLedgerApplication</c>, which this host deliberately does not call — what is
    /// under test is the translation, not the registration.
    /// </summary>
    private static MeetingsQueries QueriesIn(AsyncServiceScope scope) =>
        new(scope.ServiceProvider.GetRequiredService<IReadDb>());

    private static Meeting NewMeeting(string title) =>
        Meeting.Create(title, Held, ["Dana Whitfield"], Guid.CreateVersion7(), Created);

    private static async Task SaveAsync(IServiceProvider services, Meeting meeting, CancellationToken cancellationToken)
    {
        await using AsyncServiceScope scope = services.CreateAsyncScope();

        scope.ServiceProvider.GetRequiredService<IMeetingRepository>().Add(meeting);
        await scope.ServiceProvider.GetRequiredService<IUnitOfWork>().CommitAsync(cancellationToken);
    }

    private static async Task<Meeting> ReadAsync(IServiceProvider services, Guid id, CancellationToken cancellationToken)
    {
        await using AsyncServiceScope scope = services.CreateAsyncScope();

        return await LoadAsync(scope, id, cancellationToken);
    }

    private static async Task<Meeting> LoadAsync(AsyncServiceScope scope, Guid id, CancellationToken cancellationToken)
    {
        Meeting? meeting = await scope.ServiceProvider.GetRequiredService<IMeetingRepository>()
            .FindByIdAsync(id, cancellationToken);

        Assert.NotNull(meeting);

        return meeting;
    }

    private async Task<string> MigratedDatabaseAsync(string name, CancellationToken cancellationToken)
    {
        string connectionString = await postgres.CreateDatabaseAsync(name, cancellationToken);

        await using ServiceProvider services = TestHost.Build(connectionString, TestHost.SeedingOff);
        await TestHost.MigrateAsync(services, cancellationToken);

        return connectionString;
    }

    private async Task<ServiceProvider> MigratedHostAsync(
        string name,
        CancellationToken cancellationToken,
        Action<IServiceCollection>? configure = null)
    {
        string connectionString = await postgres.CreateDatabaseAsync(name, cancellationToken);

        ServiceProvider services = TestHost.Build(connectionString, TestHost.SeedingOff, configure);

        await TestHost.MigrateAsync(services, cancellationToken);

        return services;
    }

    private static async Task<Dictionary<string, string>> ColumnsAsync(
        string connectionString,
        string table,
        CancellationToken cancellationToken)
    {
        Dictionary<string, string> columns = new(StringComparer.Ordinal);

        await using NpgsqlConnection connection = new(connectionString);
        await connection.OpenAsync(cancellationToken);

        await using NpgsqlCommand command = new(
            """
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = @table
            """,
            connection);

        command.Parameters.AddWithValue("table", table);

        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync(cancellationToken);

        while (await reader.ReadAsync(cancellationToken))
        {
            columns[reader.GetString(0)] = reader.GetString(1);
        }

        return columns;
    }
}
